import { Building2, CheckCircle2, CircleAlert, Clock3, FileCheck2, XCircle } from "lucide-react";
import Link from "next/link";
import type { AccountValidation, Availability, ValidationStatus } from "@/features/medtrack-institutions/domain/institution-management";
import { ValidationActions } from "@/features/medtrack-institutions/ui/validation-actions";
import styles from "./institution-management.module.css";

const accountLabels: Record<string,string> = { HOSPITAL_ADMIN: "Admin hôpital", UNIVERSITY_ADMIN: "Admin université", MEDICAL_ORDER_ADMIN: "Admin Ordre", MINISTRY_AGENT: "Agent ministère", MEDTRACK_ADMIN: "Admin Medtrack" };
function date(value: string | null) { if (!value) return "—"; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? "—" : new Intl.DateTimeFormat("fr-FR", { day: "2-digit", month: "long", year: "numeric" }).format(parsed); }

/** Tableau de validation des comptes institutionnels actuellement exposés par auth-service. */
export function AccountValidationManagement({ validations, filter, availability, canReview }: Readonly<{ validations: AccountValidation[]; filter?: ValidationStatus; availability: Availability; canReview: boolean }>) {
  const counts = { total: validations.length, pending: validations.filter((v) => v.status === "PENDING").length, approved: validations.filter((v) => v.status === "APPROVED").length, rejected: validations.filter((v) => v.status === "REJECTED").length };
  return <div className={styles.page}><header className={styles.pageHeader}><div><h2>Validation des comptes</h2><p>Examinez les demandes institutionnelles avant d’autoriser leur accès à Medtrack.</p></div></header>
    {availability.kind === "ready" ? <section className={styles.metrics}><article><span className={styles.metricTeal}><FileCheck2 /></span><div><strong>{counts.total}</strong><p>Demandes affichées</p></div></article><article><span className={styles.metricAmber}><Clock3 /></span><div><strong>{counts.pending}</strong><p>En attente</p></div></article><article><span className={styles.metricBlue}><CheckCircle2 /></span><div><strong>{counts.approved}</strong><p>Approuvées</p></div></article><article><span className={styles.metricRed}><XCircle /></span><div><strong>{counts.rejected}</strong><p>Rejetées</p></div></article></section> : null}
    <nav className={styles.tabs} aria-label="Filtrer les validations"><Link className={!filter ? styles.activeTab : ""} href="/medtrack/account-validations">Toutes</Link><Link className={filter === "PENDING" ? styles.activeTab : ""} href="/medtrack/account-validations?status=PENDING">En attente</Link><Link className={filter === "APPROVED" ? styles.activeTab : ""} href="/medtrack/account-validations?status=APPROVED">Approuvées</Link><Link className={filter === "REJECTED" ? styles.activeTab : ""} href="/medtrack/account-validations?status=REJECTED">Rejetées</Link></nav>
    {!canReview && availability.kind === "ready" ? <div className={styles.infoBanner}><CircleAlert /><p>La consultation est disponible, mais seule une identité <strong>SUPER_ADMIN</strong> peut approuver ou rejeter une demande.</p></div> : null}
    {availability.kind !== "ready" ? <section className={styles.errorState} role="alert"><CircleAlert /><div><strong>{availability.kind === "forbidden" ? "Accès non autorisé" : "Auth-service indisponible"}</strong><p>{availability.message}</p>{availability.requestId ? <code>request_id : {availability.requestId}</code> : null}</div></section> : <section className={styles.tableCard}>{validations.length === 0 ? <div className={styles.emptyState}><FileCheck2 /><strong>Aucune demande</strong><p>Aucune validation ne correspond au filtre sélectionné.</p></div> : <div className={styles.tableScroll}><table className={styles.validationTable}><thead><tr><th>Demandeur</th><th>Compte demandé</th><th>Institution</th><th>Soumise le</th><th>Statut</th><th>Décision</th></tr></thead><tbody>{validations.map((validation) => <tr key={validation.uuid}><td><span className={styles.applicant}><span>{(validation.user.fullname ?? validation.user.email ?? "U").slice(0,2).toUpperCase()}</span><span><strong>{validation.user.fullname ?? "Utilisateur sans nom"}</strong><small>{validation.user.email ?? validation.user.phone_number ?? "—"}</small></span></span></td><td><strong>{accountLabels[validation.account_type] ?? validation.requested_role_code ?? validation.account_type}</strong><small className={styles.blockText}>{validation.requested_role_code}</small></td><td><span className={styles.scope}><Building2 />{validation.institution_name ?? validation.scope_uuid ?? "Portée globale"}</span></td><td>{date(validation.created_at)}</td><td><span className={`${styles.badge} ${styles[`validation_${validation.status}`]}`}>{validation.status === "PENDING" ? "En attente" : validation.status === "APPROVED" ? "Approuvée" : "Rejetée"}</span>{validation.rejection_reason ? <small className={styles.blockText}>{validation.rejection_reason}</small> : null}</td><td><ValidationActions validation={validation} canReview={canReview} /></td></tr>)}</tbody></table></div>}</section>}
  </div>;
}