import { Building2, CircleAlert, Hospital, Landmark, Search, University } from "lucide-react";
import Link from "next/link";
import type { Availability, InstitutionFilters, InstitutionListMeta, ManagedInstitution } from "@/features/medtrack-institutions/domain/institution-management";
import { InstitutionActions } from "@/features/medtrack-institutions/ui/institution-actions";
import styles from "./institution-management.module.css";

const typeLabels: Record<string, string> = { UNIVERSITY: "Université", HOSPITAL: "Hôpital", HEALTH_CENTER: "Centre de santé", CLINIC: "Clinique", MINISTRY: "Ministère", MEDICAL_ORDER: "Ordre des médecins", MEDTRACK: "Medtrack", OTHER: "Autre" };
const statusLabels: Record<string, string> = { PENDING: "En attente", ACTIVE: "Active", SUSPENDED: "Suspendue", INACTIVE: "Inactive", ARCHIVED: "Archivée" };
const verificationLabels: Record<string, string> = { UNVERIFIED: "Non vérifiée", PENDING_VERIFICATION: "À vérifier", VERIFIED: "Vérifiée", REJECTED: "Rejetée" };

type Props = Readonly<{ institutions: ManagedInstitution[]; meta: InstitutionListMeta; filters: InstitutionFilters; availability: Availability; canManage: boolean }>;
function number(value: number) { return new Intl.NumberFormat("fr-FR").format(value); }
function date(value: string | null) { if (!value) return "—"; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? "—" : new Intl.DateTimeFormat("fr-FR", { day: "2-digit", month: "short", year: "numeric" }).format(parsed); }
function href(filters: InstitutionFilters, page: number) { const q = new URLSearchParams({ page: String(page) }); if (filters.search) q.set("search", filters.search); if (filters.institutionType) q.set("institution_type", filters.institutionType); if (filters.status) q.set("status", filters.status); if (filters.verificationStatus) q.set("verification_status", filters.verificationStatus); return `/medtrack/institutions?${q}`; }

/** Registre responsive, fidèle au langage visuel global de l’espace Medtrack. */
export function InstitutionManagement({ institutions, meta, filters, availability, canManage }: Props) {
  const visibleUniversities = institutions.filter((item) => item.institution_type === "UNIVERSITY").length;
  const visibleHospitals = institutions.filter((item) => item.institution_type === "HOSPITAL" || item.institution_type === "CLINIC").length;
  const visiblePending = institutions.filter((item) => item.verification_status === "PENDING_VERIFICATION" || item.verification_status === "UNVERIFIED").length;
  return <div className={styles.page}>
    <header className={styles.pageHeader}><div><h2>Gestion des institutions</h2><p>Supervisez les établissements enregistrés et leur statut de vérification.</p></div><div className={styles.headerAction}><InstitutionActions canManage={canManage} />{!canManage ? <small>Permission de gestion requise.</small> : null}</div></header>
    {availability.kind === "ready" ? <section className={styles.metrics} aria-label="Indicateurs institutions">
      <article><span className={styles.metricTeal}><Building2 /></span><div><strong>{number(meta.total)}</strong><p>Institutions enregistrées</p></div></article>
      <article><span className={styles.metricBlue}><University /></span><div><strong>{visibleUniversities}</strong><p>Universités sur cette page</p></div></article>
      <article><span className={styles.metricAmber}><Hospital /></span><div><strong>{visibleHospitals}</strong><p>Hôpitaux et cliniques</p></div></article>
      <article><span className={styles.metricRed}><Landmark /></span><div><strong>{visiblePending}</strong><p>À vérifier sur cette page</p></div></article>
    </section> : null}
    <form method="get" className={styles.filters}><label className={styles.search}><Search /><input name="search" defaultValue={filters.search ?? ""} placeholder="Rechercher une institution..." minLength={2} /></label><select name="institution_type" defaultValue={filters.institutionType ?? ""} aria-label="Type d’institution"><option value="">Tous les types</option>{Object.entries(typeLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><select name="status" defaultValue={filters.status ?? ""} aria-label="Statut"><option value="">Tous les statuts</option>{Object.entries(statusLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><select name="verification_status" defaultValue={filters.verificationStatus ?? ""} aria-label="Vérification"><option value="">Toutes les vérifications</option>{Object.entries(verificationLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><button type="submit" className={styles.filterButton}>Appliquer</button><Link href="/medtrack/institutions" className={styles.reset}>Réinitialiser</Link></form>
    {availability.kind !== "ready" ? <section className={styles.errorState} role="alert"><CircleAlert /><div><strong>{availability.kind === "forbidden" ? "Accès non autorisé" : "Institution-service indisponible"}</strong><p>{availability.message}</p>{availability.requestId ? <code>request_id : {availability.requestId}</code> : null}</div></section> : <section className={styles.tableCard}><div className={styles.tableHeading}><div><h3>Liste des institutions</h3><p>{number(meta.total)} établissement(s)</p></div></div>{institutions.length === 0 ? <div className={styles.emptyState}><Building2 /><strong>Aucune institution trouvée</strong><p>Modifiez vos filtres ou créez le premier établissement.</p></div> : <div className={styles.tableScroll}><table><thead><tr><th>Institution</th><th>Type</th><th>Code officiel</th><th>Statut</th><th>Vérification</th><th>Créée le</th><th>Actions</th></tr></thead><tbody>{institutions.map((institution) => <tr key={institution.uuid}><td><span className={styles.institutionIdentity}><span><Building2 /></span><span><strong>{institution.display_name ?? institution.legal_name}</strong><small>{institution.legal_name}</small></span></span></td><td>{typeLabels[institution.institution_type] ?? institution.institution_type}</td><td>{institution.official_code ?? "—"}</td><td><span className={`${styles.badge} ${styles[`status_${institution.status}`]}`}>{statusLabels[institution.status] ?? institution.status}</span></td><td><span className={`${styles.badge} ${styles[`verification_${institution.verification_status}`]}`}>{verificationLabels[institution.verification_status] ?? institution.verification_status}</span></td><td>{date(institution.created_at)}</td><td><InstitutionActions institution={institution} canManage={canManage} /></td></tr>)}</tbody></table></div>}{meta.last_page > 1 ? <nav className={styles.pagination}><span>Page {meta.current_page} sur {meta.last_page}</span><div>{meta.current_page > 1 ? <Link href={href(filters, meta.current_page - 1)}>Précédent</Link> : <span>Précédent</span>}{meta.current_page < meta.last_page ? <Link href={href(filters, meta.current_page + 1)}>Suivant</Link> : <span>Suivant</span>}</div></nav> : null}</section>}
  </div>;
}