import { type NextRequest, NextResponse } from "next/server";
import { ApiError } from "@/core/api/api-error";
import { apiRequest } from "@/core/api/http-client";
import { getCurrentSession } from "@/core/auth/auth-session";
import { isSameOriginRequest } from "@/core/security/same-origin";
import type { AccountValidation } from "@/features/medtrack-institutions/domain/institution-management";
type Context = { params: Promise<{ validationUuid: string }> }; type ValidationEnvelope = { data: AccountValidation[] }; type InstitutionEnvelope = { data: { uuid: string } }; const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
/** Saga BFF idempotente : institution d’abord, identité ensuite, sans HTTP interservice. */
export async function PATCH(request: NextRequest, context: Context) {
  if (!isSameOriginRequest(request)) return NextResponse.json({ title: "Origine interdite" }, { status: 403 }); const session = await getCurrentSession(); if (!session) return NextResponse.json({ title: "Session expirée" }, { status: 401 }); if (!session.user.roles.includes("SUPER_ADMIN")) return NextResponse.json({ title: "Accès interdit" }, { status: 403 }); const { validationUuid } = await context.params; if (!uuid.test(validationUuid)) return NextResponse.json({ title: "UUID de demande invalide" }, { status: 422 });
  try { const listed = await apiRequest<ValidationEnvelope>("/auth/v1/admin/account-validations", { accessToken: session.auth.accessToken }); const validation = listed.data.find((item) => item.uuid === validationUuid); if (!validation) return NextResponse.json({ title: "Demande introuvable" }, { status: 404 }); let institutionUuid: string | undefined; if (validation.validation_source === "institution_onboarding") { if (!validation.onboarding_request_uuid || !uuid.test(validation.onboarding_request_uuid)) return NextResponse.json({ title: "Demande institutionnelle incohérente" }, { status: 409 }); const institution = await apiRequest<InstitutionEnvelope>(`/institution/v1/admin/onboarding-requests/${validation.onboarding_request_uuid}/approve`, { method: "PATCH", accessToken: session.auth.accessToken, body: {} }); institutionUuid = institution.data.uuid; } const response = await apiRequest<Record<string, unknown>>(`/auth/v1/admin/account-validations/${validationUuid}/approve`, { method: "PATCH", accessToken: session.auth.accessToken, body: institutionUuid ? { institution_uuid: institutionUuid } : {} }); return NextResponse.json(response); } catch (error) { if (error instanceof ApiError) return NextResponse.json(error.problem ?? { title: error.message }, { status: error.status }); return NextResponse.json({ title: "Workflow de validation indisponible" }, { status: 503 }); }
}